#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
AOSP_TAG="${AOSP_TAG:-android-16.0.0_r4}"
AOSP_TAG_REF="refs/tags/${AOSP_TAG}"
lock="$root/revisions.lock"
manifest="$root/manifests/axion-arm64-prebuilts.xml"

resolve() {
  local repo="$1" ref="$2" sha
  sha="$(git ls-remote "$repo" "$ref" | awk 'NR==1 {print $1}')"
  if [[ -z "$sha" ]]; then
    echo "error: unable to resolve $repo $ref" >&2
    exit 1
  fi
  printf '%s' "$sha"
}

manifest_repo="https://android.googlesource.com/platform/manifest"
manifest_sha="$(resolve "$manifest_repo" "$AOSP_TAG_REF")"

# Android 16 compatibility anchors. These are the exact x86/tagged prebuilts
# selected by the platform manifest at android-16.0.0_r4.
clang_x86_tag_sha="$(resolve https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86 "$AOSP_TAG_REF")"
cmake_x86_tag_sha="$(resolve https://android.googlesource.com/platform/prebuilts/cmake/linux-x86 "$AOSP_TAG_REF")"
go_x86_tag_sha="$(resolve https://android.googlesource.com/platform/prebuilts/go/linux-x86 "$AOSP_TAG_REF")"
build_tools_tag_sha="$(resolve https://android.googlesource.com/platform/prebuilts/build-tools "$AOSP_TAG_REF")"
jdk8_tag_sha="$(resolve https://android.googlesource.com/platform/prebuilts/jdk/jdk8 "$AOSP_TAG_REF")"
jdk21_tag_sha="$(resolve https://android.googlesource.com/platform/prebuilts/jdk/jdk21 "$AOSP_TAG_REF")"

# Linux ARM64 host prebuilts were published on dedicated mirror branches rather
# than the Android 16 release tag. Resolve their current branch heads and pin
# the resulting SHAs in the generated manifest.
clang_arm64_ref="refs/heads/mirror-goog-main-prebuilts"
cmake_arm64_ref="refs/heads/mirror-goog-main-prebuilts"
go_arm64_ref="refs/heads/mirror-goog-llvm-r596125-release"
ninja_arm64_ref="refs/heads/mirror-goog-main-prebuilts"
python_arm64_ref="refs/heads/mirror-goog-llvm-r596125-release"

clang_arm64_sha="$(resolve https://android.googlesource.com/platform/prebuilts/clang/host/linux-arm64 "$clang_arm64_ref")"
cmake_arm64_sha="$(resolve https://android.googlesource.com/platform/prebuilts/cmake/linux-arm64 "$cmake_arm64_ref")"
go_arm64_sha="$(resolve https://android.googlesource.com/platform/prebuilts/go/linux-arm64 "$go_arm64_ref")"
ninja_arm64_sha="$(resolve https://android.googlesource.com/platform/prebuilts/ninja/linux-arm64 "$ninja_arm64_ref")"
python_arm64_sha="$(resolve https://android.googlesource.com/platform/prebuilts/python/linux-arm64 "$python_arm64_ref")"

cat >"$lock" <<EOF
AOSP_TAG=$AOSP_TAG
AOSP_TAG_REF=$AOSP_TAG_REF
AOSP_MANIFEST_SHA=$manifest_sha

CLANG_X86_TAG_SHA=$clang_x86_tag_sha
CMAKE_X86_TAG_SHA=$cmake_x86_tag_sha
GO_X86_TAG_SHA=$go_x86_tag_sha
BUILD_TOOLS_TAG_SHA=$build_tools_tag_sha
JDK8_TAG_SHA=$jdk8_tag_sha
JDK21_TAG_SHA=$jdk21_tag_sha

CLANG_ARM64_REF=$clang_arm64_ref
CLANG_ARM64_SHA=$clang_arm64_sha
CMAKE_ARM64_REF=$cmake_arm64_ref
CMAKE_ARM64_SHA=$cmake_arm64_sha
GO_ARM64_REF=$go_arm64_ref
GO_ARM64_SHA=$go_arm64_sha
NINJA_ARM64_REF=$ninja_arm64_ref
NINJA_ARM64_SHA=$ninja_arm64_sha
PYTHON_ARM64_REF=$python_arm64_ref
PYTHON_ARM64_SHA=$python_arm64_sha
EOF

cat >"$manifest" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <!-- Generated by scripts/update-revisions.sh for $AOSP_TAG_REF. -->
  <remote name="aosp-arm64" fetch="https://android.googlesource.com/" />
  <remote name="github-arm64" fetch="https://github.com/" />

  <project path="prebuilts/clang/host/linux-arm64"
           name="platform/prebuilts/clang/host/linux-arm64"
           remote="aosp-arm64"
           revision="$clang_arm64_sha" />

  <project path="prebuilts/go/linux-arm64"
           name="platform/prebuilts/go/linux-arm64"
           remote="aosp-arm64"
           revision="$go_arm64_sha" />

  <project path="prebuilts/cmake/linux-arm64"
           name="platform/prebuilts/cmake/linux-arm64"
           remote="aosp-arm64"
           revision="$cmake_arm64_sha" />

  <project path="prebuilts/ninja/linux-arm64"
           name="platform/prebuilts/ninja/linux-arm64"
           remote="aosp-arm64"
           revision="$ninja_arm64_sha" />

  <project path="prebuilts/python/linux-arm64"
           name="platform/prebuilts/python/linux-arm64"
           remote="aosp-arm64"
           revision="$python_arm64_sha" />

  <project path="prebuilts/arm64-host"
           name="divyam234/android-arm64-prebuilts"
           remote="github-arm64"
           revision="main">
    <linkfile src="prebuilts/rust-toolchain/linux-arm64"
              dest="prebuilts/rust-toolchain/linux-arm64" />
    <linkfile src="prebuilts/jdk/jdk8/linux-arm64"
              dest="prebuilts/jdk/jdk8/linux-arm64" />
    <linkfile src="prebuilts/jdk/jdk21/linux-arm64"
              dest="prebuilts/jdk/jdk21/linux-arm64" />
  </project>
</manifest>
EOF

printf 'Updated %s and %s\n' "$lock" "$manifest"
printf 'Base Android tag: %s (%s)\n' "$AOSP_TAG_REF" "$manifest_sha"
