#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
AOSP_TAG="${AOSP_TAG:-android-16.0.0_r4}"
AOSP_TAG_REF="refs/tags/${AOSP_TAG}"
lock="$root/revisions.lock"
manifest="$root/manifests/axion-arm64-prebuilts.xml"

resolve() {
  local repo="$1" ref="$2" sha
  sha="$(git ls-remote "$repo" "$ref" | awk 'NR==1 {print $1}')"
  if [[ -z "$sha" ]]; then
    echo "error: unable to resolve $repo $ref" >&2
    exit 1
  fi
  printf '%s' "$sha"
}

aosp="https://android.googlesource.com"
manifest_sha="$(resolve "$aosp/platform/manifest" "$AOSP_TAG_REF")"
jdk8_tag_sha="$(resolve "$aosp/platform/prebuilts/jdk/jdk8" "$AOSP_TAG_REF")"
jdk21_tag_sha="$(resolve "$aosp/platform/prebuilts/jdk/jdk21" "$AOSP_TAG_REF")"
build_tools_tag_sha="$(resolve "$aosp/platform/prebuilts/build-tools" "$AOSP_TAG_REF")"

# These ARM64 host prebuilts are maintained by Google in dedicated AOSP mirror
# branches. We consume them directly and pin the branch heads to exact SHAs.
clang_ref="refs/heads/mirror-goog-main-prebuilts"
go_ref="refs/heads/mirror-goog-llvm-r596125-release"
cmake_ref="refs/heads/mirror-goog-main-prebuilts"
ninja_ref="refs/heads/mirror-goog-main-prebuilts"
python_ref="refs/heads/mirror-goog-llvm-r596125-release"

clang_sha="$(resolve "$aosp/platform/prebuilts/clang/host/linux-arm64" "$clang_ref")"
go_sha="$(resolve "$aosp/platform/prebuilts/go/linux-arm64" "$go_ref")"
cmake_sha="$(resolve "$aosp/platform/prebuilts/cmake/linux-arm64" "$cmake_ref")"
ninja_sha="$(resolve "$aosp/platform/prebuilts/ninja/linux-arm64" "$ninja_ref")"
python_sha="$(resolve "$aosp/platform/prebuilts/python/linux-arm64" "$python_ref")"

cat >"$lock" <<EOF
AOSP_TAG=$AOSP_TAG
AOSP_TAG_REF=$AOSP_TAG_REF
AOSP_MANIFEST_SHA=$manifest_sha

BUILD_TOOLS_TAG_SHA=$build_tools_tag_sha
JDK8_TAG_SHA=$jdk8_tag_sha
JDK21_TAG_SHA=$jdk21_tag_sha

CLANG_ARM64_REF=$clang_ref
CLANG_ARM64_SHA=$clang_sha
GO_ARM64_REF=$go_ref
GO_ARM64_SHA=$go_sha
CMAKE_ARM64_REF=$cmake_ref
CMAKE_ARM64_SHA=$cmake_sha
NINJA_ARM64_REF=$ninja_ref
NINJA_ARM64_SHA=$ninja_sha
PYTHON_ARM64_REF=$python_ref
PYTHON_ARM64_SHA=$python_sha
EOF

cat >"$manifest" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <!-- Generated by scripts/update-revisions.sh for $AOSP_TAG_REF. -->
  <remote name="aosp-arm64" fetch="https://android.googlesource.com/" />
  <remote name="github-arm64" fetch="https://github.com/" />

  <!-- Google-maintained ARM64 host prebuilts: consume directly from AOSP. -->
  <project path="prebuilts/clang/host/linux-arm64"
           name="platform/prebuilts/clang/host/linux-arm64"
           remote="aosp-arm64"
           revision="$clang_sha" />

  <project path="prebuilts/go/linux-arm64"
           name="platform/prebuilts/go/linux-arm64"
           remote="aosp-arm64"
           revision="$go_sha" />

  <project path="prebuilts/cmake/linux-arm64"
           name="platform/prebuilts/cmake/linux-arm64"
           remote="aosp-arm64"
           revision="$cmake_sha" />

  <project path="prebuilts/ninja/linux-arm64"
           name="platform/prebuilts/ninja/linux-arm64"
           remote="aosp-arm64"
           revision="$ninja_sha" />

  <project path="prebuilts/python/linux-arm64"
           name="platform/prebuilts/python/linux-arm64"
           remote="aosp-arm64"
           revision="$python_sha" />

  <!-- Our repo only carries prebuilts missing from AOSP for this host setup. -->
  <project path="prebuilts/arm64-host"
           name="divyam234/android-arm64-prebuilts"
           remote="github-arm64"
           revision="main">
    <linkfile src="prebuilts/rust-toolchain/linux-arm64"
              dest="prebuilts/rust-toolchain/linux-arm64" />
    <linkfile src="prebuilts/jdk/jdk8/linux-arm64"
              dest="prebuilts/jdk/jdk8/linux-arm64" />
    <linkfile src="prebuilts/jdk/jdk21/linux-arm64"
              dest="prebuilts/jdk/jdk21/linux-arm64" />
  </project>
</manifest>
EOF

printf 'Updated %s and %s\n' "$lock" "$manifest"
printf 'Base Android tag: %s (%s)\n' "$AOSP_TAG_REF" "$manifest_sha"
printf 'AOSP ARM64: clang=%s go=%s cmake=%s ninja=%s python=%s\n' \
  "$clang_sha" "$go_sha" "$cmake_sha" "$ninja_sha" "$python_sha"
